name: fluddit
description: An open source Reddit client written in Flutter.
publish_to: 'none'
version: 0.1.4+14

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_nord_theme: ^2.1.0
  get: ^4.2.5
  get_storage: ^2.0.3
  http: ^0.13.3
  video_player: ^2.1.12
  webview_flutter: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  assets:
    - 'lib/assets/redditIcon.png'
  uses-material-design: true