name: fluddit
description: An open source Reddit client written in Flutter.
publish_to: 'none'
version: 0.1.1+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  get: ^4.2.5
  flutter_nord_theme: ^2.1.0
  shared_preferences: ^2.0.6
  video_player: ^2.1.12
  carousel_slider: ^4.0.0
  webview_flutter: ^2.0.12
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - 'lib/assets/redditIcon.png'